In [1]:
from tensorflow.keras.preprocessing.text import one_hot

2026-05-17 20:54:32.193998: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


apply the one-hot encodert

In [2]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good boy',
    'i am a good developer',
    'understand the meaning of the word',
    'your videos are good'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good boy',
 'i am a good developer',
 'understand the meaning of the word',
 'your videos are good']

In [4]:
voc_size=10000

In [5]:
one_hot_rep=[one_hot(words,voc_size)for words in sent]
one_hot_rep
    

[[4024, 1197, 1320, 5968],
 [4024, 1197, 1320, 5992],
 [4024, 1205, 1320, 3539],
 [7421, 3471, 5593, 248, 8458],
 [7421, 3471, 5593, 248, 7467],
 [5133, 4024, 8233, 1320, 4024, 526],
 [3904, 3357, 5858, 248]]

word embedding representation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sen_length=8
Embedded_docs=pad_sequences(one_hot_rep,padding='post',maxlen=sen_length)
print(Embedded_docs)

[[4024 1197 1320 5968    0    0    0    0]
 [4024 1197 1320 5992    0    0    0    0]
 [4024 1205 1320 3539    0    0    0    0]
 [7421 3471 5593  248 8458    0    0    0]
 [7421 3471 5593  248 7467    0    0    0]
 [5133 4024 8233 1320 4024  526    0    0]
 [3904 3357 5858  248    0    0    0    0]]


In [9]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sen_length))
model.compile('adam','mse')

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
model.predict(Embedded_docs)

1/1 [==============================] - 0s 68ms/step


array([[[-0.00736861,  0.02579942,  0.04996702, -0.00397737,
          0.04655076, -0.0090601 , -0.03491666,  0.03355588,
          0.03140673,  0.02852998],
        [ 0.03658942,  0.02661433,  0.02331932,  0.00792918,
          0.00650675,  0.01630348,  0.02671451,  0.04265952,
         -0.03393632,  0.01527984],
        [-0.00272257, -0.04951481, -0.0027554 ,  0.0158592 ,
          0.04658849,  0.01502803, -0.04333668,  0.04061801,
          0.03225192,  0.04272299],
        [ 0.04848709, -0.04863922, -0.03571916, -0.0024833 ,
         -0.02095553, -0.02648165, -0.04439076, -0.0472739 ,
         -0.03985637, -0.04933767],
        [ 0.02036643, -0.01196132,  0.03984017,  0.03718268,
         -0.01902058,  0.02448125, -0.04295989,  0.03064444,
         -0.00205181,  0.02789888],
        [ 0.02036643, -0.01196132,  0.03984017,  0.03718268,
         -0.01902058,  0.02448125, -0.04295989,  0.03064444,
         -0.00205181,  0.02789888],
        [ 0.02036643, -0.01196132,  0.03984017,  0.0

In [12]:
Embedded_docs[0]

array([4024, 1197, 1320, 5968,    0,    0,    0,    0], dtype=int32)

In [13]:
model.predict(Embedded_docs[0])

1/1 [==============================] - 0s 39ms/step


array([[-0.00736861,  0.02579942,  0.04996702, -0.00397737,  0.04655076,
        -0.0090601 , -0.03491666,  0.03355588,  0.03140673,  0.02852998],
       [ 0.03658942,  0.02661433,  0.02331932,  0.00792918,  0.00650675,
         0.01630348,  0.02671451,  0.04265952, -0.03393632,  0.01527984],
       [-0.00272257, -0.04951481, -0.0027554 ,  0.0158592 ,  0.04658849,
         0.01502803, -0.04333668,  0.04061801,  0.03225192,  0.04272299],
       [ 0.04848709, -0.04863922, -0.03571916, -0.0024833 , -0.02095553,
        -0.02648165, -0.04439076, -0.0472739 , -0.03985637, -0.04933767],
       [ 0.02036643, -0.01196132,  0.03984017,  0.03718268, -0.01902058,
         0.02448125, -0.04295989,  0.03064444, -0.00205181,  0.02789888],
       [ 0.02036643, -0.01196132,  0.03984017,  0.03718268, -0.01902058,
         0.02448125, -0.04295989,  0.03064444, -0.00205181,  0.02789888],
       [ 0.02036643, -0.01196132,  0.03984017,  0.03718268, -0.01902058,
         0.02448125, -0.04295989,  0.03064444